version: '3.8'

services:
  web:
    container_name: 'web'
    image: nginx:latest
    depends_on:
      - flask
      - react
    ports:
      - '80:80'

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  flask:
    container_name: 'flask'
    image: airat696/todo_list_flask:0.6
    build: .
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./var:/app/var
    ports:
      - '5000:5000'
    command: python app.py

  react:
    container_name: 'react'
    image: airat696/todo_list_react:0.7
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: on-failure
